services:
  postgres:

    container_name: microsoft-security-prediction-database
    image: postgres:latest

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: microsoft-security

    ports:
      - "5433:5432"

  pgadmin:
    container_name: microsoft-security-prediction-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "8080:80"
    depends_on:
      - postgres
