version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sbd2_postgres
    environment:
      POSTGRES_DB: sbd2_lakehouse
      POSTGRES_USER: sbd2_user
      POSTGRES_PASSWORD: sbd2_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sbd2_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sbd2_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sbd2.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - sbd2_network

volumes:
  postgres_data:

networks:
  sbd2_network:
    driver: bridge
